version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: Install Maven dependencies
          command: mvn install -DskipTests=true
      - run:
          name: Run unit tests
          command: mvn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: master
