version: 2.1
jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: mvn clean test

      - run:
          name: Générer le rapport coco
          command: mvn jacoco:report
      - run:
          name: Télécharger le rapport sur coco
          command: |
            curl -s https://codecov.io/bash | bash -s -- -t ${CODECOV_TOKEN}

      - run:
          name: Générer la Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Déployer la Javadoc sur GitHub Pages
          command: |
            git config --global user.email "dorian084270@gmail.com"
            git config --global user.name "Dorian Dallon"
            git clone --branch gh-pages https://github.com/DorianDallon1/ceri-m1-techniques-de-test.git gh-pages
            rm -rf gh-pages/*
            cp -R target/site/apidocs/* gh-pages/
            cd gh-pages
            git add .
            git commit -m "Mise à jour de la Javadoc"
            git push origin gh-pages
workflows:
  version: 2
  test:
    jobs:
      - test